# Backstage override configuration for your local development environment

auth:
  environment: development
  providers:
    github:
      development:
        clientId: "Ov23liRDHFJrBUbG16Nt"
        clientSecret: "42b3869abc5de4fc09385bc59ecae8336cf40cb7"
        ## uncomment if using GitHub Enterprise
        # enterpriseInstanceUrl: ${AUTH_GITHUB_ENTERPRISE_INSTANCE_URL}
        ## uncomment to set lifespan of user session
        # sessionDuration: { hours: 24 } # supports `ms` library format (e.g. '24h', '2 days'), ISO duration, "human duration" as used in code
        # signIn:
        #   resolvers:
        #     # See https://backstage.io/docs/auth/github/provider#resolvers for more resolvers
        #     - resolver: usernameMatchingUserEntityName

